/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    HotkeyPicker: typeof import('./components/HotkeyPicker.vue')['default']
    InputRangeNumber: typeof import('./components/BaseComponents/InputRangeNumber.vue')['default']
    InputRangeNumberSegment: typeof import('./components/BaseComponents/InputRangeNumberSegment.vue')['default']
    InputTextNumber: typeof import('./components/BaseComponents/InputTextNumber.vue')['default']
    InputTimeFormatted: typeof import('./components/BaseComponents/InputTimeFormatted.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    QuickTagButtons: typeof import('./components/QuickTagButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCustom: typeof import('./components/BaseComponents/SelectCustom.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Soundboard: typeof import('./components/Soundboard.vue')['default']
    SoundButton: typeof import('./components/SoundButton.vue')['default']
    SoundEditor: typeof import('./components/SoundEditor.vue')['default']
    SoundToolbar: typeof import('./components/SoundToolbar.vue')['default']
    SystemInformation: typeof import('./components/SystemInformation.vue')['default']
    TagInput: typeof import('./components/BaseComponents/TagInput.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
    Toggle: typeof import('./components/BaseComponents/Toggle.vue')['default']
  }
}
